import { InfoCircleOutlined, PlusCircleFilled, PlusCircleOutlined, PlusCircleTwoTone, UpOutlined, UploadOutlined, CameraOutlined, DownOutlined, DeleteOutlined, PlusOutlined } from '@ant-design/icons-vue';
import antd from 'ant-design-vue';
import Antdm from 'antd-mobile-vue-next';
import Element from 'element-plus';
import vant from 'vant';
import 'vant/lib/index.css';
import { createApp } from 'vue';
import CodeContainer from './components/code-container.vue';
import CodeEditor from './components/code-editor.vue';
import DemoWrapper from './components/demo-wrapper.vue';
import router from './router';
import SchemaForm from './schema-form';
import './styles';
import './styles/github-markdown.less';
import App from './views/index.vue';
import ShowValue from './views/show-value.vue';

const app = createApp(App);
app.config.warnHandler = () => {
  // do not show
};
app.use(Antdm);
app.use(Element);
app.use(router as any);
app.use(vant);
app.use(antd as any);
app.use(SchemaForm);
app.component('DemoWrapper', DemoWrapper);
app.component('CodeContainer', CodeContainer);
app.component('CodeEditor', CodeEditor);
app.component('ShowValue', ShowValue);
app.component('InfoCircleOutlined', InfoCircleOutlined);
app.component('UpOutlined', UpOutlined);
app.component('DownOutlined', DownOutlined);
app.component('DeleteOutlined', DeleteOutlined);
app.component('PlusOutlined', PlusOutlined);
app.component('UploadOutlined', UploadOutlined);
app.component('CameraOutlined', CameraOutlined);
app.component('PlusCircleOutlined', PlusCircleOutlined);
app.component('PlusCircleTwoTone', PlusCircleTwoTone);
app.component('PlusCircleFilled', PlusCircleFilled);
app.mount('#app');
